#!/bin/bash
# Quick viewer for EDA visualizations

echo "=========================================="
echo "EDA Visualization Browser"
echo "=========================================="
echo ""
echo "Generated visualizations:"
echo ""
echo "[ENTITY] $(ls data/eda/viz/entity/*.png | wc -l | tr -d ' ') files"
echo "[CLAIM]  $(ls data/eda/viz/claim/*.png | wc -l | tr -d ' ') files"
echo ""
echo "Key visualizations to review:"
echo ""
echo "1. Co-occurrence Analysis:"
echo "   open data/eda/viz/entity/entity_cooccurrence_heatmap.png"
echo "   open data/eda/viz/claim/claim_cooccurrence_heatmap.png"
echo ""
echo "2. Message Patterns:"
echo "   open data/eda/viz/entity/entity_message_patterns.png"
echo "   open data/eda/viz/claim/claim_message_patterns.png"
echo ""
echo "3. Character Patterns:"
echo "   open data/eda/viz/entity/entity_character_patterns.png"
echo "   open data/eda/viz/claim/claim_character_patterns.png"
echo ""
echo "4. Top Terms (examples):"
echo "   open data/eda/viz/entity/entity_top_terms_ACTION_REQUIRED.png"
echo "   open data/eda/viz/claim/claim_top_terms_FINANCIAL_CLAIM.png"
echo ""
echo "----------------------------------------"
echo "Quick Actions:"
echo "----------------------------------------"
echo ""
echo "View all entity visualizations:"
echo "  open data/eda/viz/entity/"
echo ""
echo "View all claim visualizations:"
echo "  open data/eda/viz/claim/"
echo ""
echo "Open all key visualizations:"
echo "  ./view_key_viz.sh"
echo ""
echo "=========================================="

# Uncomment to open key visualizations automatically:
# open data/eda/viz/entity/entity_cooccurrence_heatmap.png
# open data/eda/viz/claim/claim_cooccurrence_heatmap.png
# open data/eda/viz/entity/entity_message_patterns.png
# open data/eda/viz/claim/claim_message_patterns.png
